r"""The PowerShell tab completer, generated from the catalogue.

Layer: L4 — `leasha completions --powershell`.

**Generated, never hand-written.** A completer typed out by hand is a second
copy of the grammar, and this project's one non-negotiable for commands is a
single catalogue feeding every consumer. Regenerating after a catalogue change
is the update path, and a test asserts the emitted script names every command
`COMMANDS` does.

**Two steps, and the order matters.** The script reads `completions.json`
first - a file, no process, no Python - and falls back to `suggest.py` only for
a source the sidecar has no entry for. The measurements behind that split are
in `suggest.py`'s docstring; the short version is that starting `app.cli` costs
243ms against a budget of 300ms for the whole keypress.

**The tab completer offers unscoped values, deliberately.** Conditioning them
on the half-typed query would mean parsing that query inside a PowerShell
script block - a second parser in a second language, which is the drift this
order's §5 forbids. Scoped completion in a terminal is what `leasha shell` is
for, where the parser is the same Python one the window uses.

Qt-free, and it emits text rather than writing files, so what it produces can
be read in a test without a shell.
"""

from __future__ import annotations

from typing import Any, Optional

__all__ = ["completer_script", "PROFILE_MARKER"]

#: The line that says a profile already has this. Used to install once and to
#: find what to remove - the same contract `add-to-path.ps1` established.
PROFILE_MARKER = "# Leasha tab completion"


def _escape(text: Any) -> str:
    """A PowerShell single-quoted string. `'` doubles; nothing else is special."""
    return str(text or "").replace("'", "''")


def completer_script(commands: Any = None, subcommands: Any = None,
                     project_path: Any = None) -> str:
    """The `Register-ArgumentCompleter` script, as text.

    `commands` and `subcommands` are injectable so the emitted script can be
    checked against a known catalogue in a test without a shell, and so the
    Code tab's switches could be emitted the same way later.
    """
    if commands is None:
        from app.search.commands import COMMANDS as commands
    if subcommands is None:
        subcommands = _subcommands()

    root = _escape(project_path or "")
    filters = "\n".join(
        f"    @{{ Name = '{_escape(c.name)}'; "
        f"Source = '{_escape(c.source)}'; "
        f"Tip = '{_escape(c.summary)}' }}"
        for c in commands
    )
    verbs = ", ".join(f"'{_escape(name)}'" for name in subcommands)

    return f"""{PROFILE_MARKER} - generated by `leasha completions --powershell`.
# Regenerate after changing the filter catalogue; do not edit by hand.
$LeashaRoot = '{root}'

function Get-LeashaSidecar {{
    # The file the indexer leaves beside the index. No process is started for
    # the overwhelming majority of Tab presses, which is the whole design.
    $envFile = Join-Path $LeashaRoot '.env'
    if (-not (Test-Path -LiteralPath $envFile)) {{ return $null }}
    $dataPath = (Get-Content -LiteralPath $envFile |
        Where-Object {{ $_ -match '^\\s*DATA_PATH\\s*=' }} |
        Select-Object -First 1) -replace '^\\s*DATA_PATH\\s*=\\s*', ''
    $dataPath = $dataPath.Trim().Trim('"')
    if (-not $dataPath) {{ return $null }}
    $file = Join-Path $dataPath 'completions.json'
    if (-not (Test-Path -LiteralPath $file)) {{ return $null }}
    try {{ return (Get-Content -LiteralPath $file -Raw | ConvertFrom-Json) }}
    catch {{ return $null }}
}}

function Get-LeashaValues($source, $prefix) {{
    $sidecar = Get-LeashaSidecar
    if ($sidecar -and $sidecar.sources.PSObject.Properties.Name -contains $source) {{
        return $sidecar.sources.$source |
            Where-Object {{ -not $prefix -or $_.value -like "*$prefix*" }} |
            ForEach-Object {{ $_.value }}
    }}
    # Only when the sidecar has no entry for this source: a source that was
    # empty at index time, or a prefix past the values it holds.
    $script = Join-Path $LeashaRoot 'suggest.py'
    $python = Join-Path $LeashaRoot 'venv\\Scripts\\python.exe'
    if ((Test-Path -LiteralPath $script) -and (Test-Path -LiteralPath $python)) {{
        try {{ return & $python $script $source $prefix }} catch {{ return @() }}
    }}
    return @()
}}

$LeashaFilters = @(
{filters}
)

Register-ArgumentCompleter -Native -CommandName leasha -ScriptBlock {{
    param($wordToComplete, $commandAst, $cursorPosition)

    # A `name:` being completed - offer its values.
    if ($wordToComplete -match '^([A-Za-z-]+):(.*)$') {{
        $name = $Matches[1]
        $partial = $Matches[2]
        $filter = $LeashaFilters | Where-Object {{ $_.Name -eq $name }} | Select-Object -First 1
        if ($filter -and $filter.Source) {{
            foreach ($value in (Get-LeashaValues $filter.Source $partial)) {{
                [System.Management.Automation.CompletionResult]::new(
                    "$name`:$value", "$name`:$value", 'ParameterValue', $filter.Tip)
            }}
            return
        }}
    }}

    # Nothing typed yet, or a bare word: the subcommands and the filter names.
    foreach ($verb in @({verbs})) {{
        if (-not $wordToComplete -or $verb -like "$wordToComplete*") {{
            [System.Management.Automation.CompletionResult]::new(
                $verb, $verb, 'ParameterName', $verb)
        }}
    }}
    foreach ($filter in $LeashaFilters) {{
        $token = "$($filter.Name):"
        if (-not $wordToComplete -or $token -like "$wordToComplete*") {{
            # The summary becomes the tooltip, which is this shell's inline
            # metadata - the same thing the dropdown shows beside each row.
            [System.Management.Automation.CompletionResult]::new(
                $token, $token, 'ParameterName', $filter.Tip)
        }}
    }}
}}
"""


def _subcommands() -> tuple[str, ...]:
    """Every verb `build_parser` registers, read from the parser itself.

    From the parser rather than from a list, for the reason the whole module
    exists: a hand-written second copy is what drifts.
    """
    import argparse

    from app.cli import build_parser

    found: list[str] = []
    for action in build_parser()._actions:
        if isinstance(action, argparse._SubParsersAction):
            found.extend(sorted(action.choices))
    return tuple(found)


def profile_lines(script_path: Any) -> str:
    """What `completions install` appends to a PowerShell profile.

    A dot-source of the generated file rather than the script inlined, so
    regenerating after a catalogue change does not need the profile edited
    again - the same shape `add-to-path.ps1` uses, and the same no-admin rule.
    """
    return (f"{PROFILE_MARKER}\n"
            f". '{_escape(script_path)}'\n")


def strip_profile(text: str) -> str:
    """`text` with the completion block removed. Idempotent.

    Removes the marker and the line after it, which is the whole block. A
    profile is somebody's own file: this must take out exactly what was put in
    and touch nothing else.
    """
    out: list[str] = []
    lines = (text or "").splitlines()
    index = 0
    while index < len(lines):
        if lines[index].strip().startswith(PROFILE_MARKER):
            index += 2                           # the marker and the dot-source
            continue
        out.append(lines[index])
        index += 1
    while out and not out[-1].strip():
        out.pop()
    return "\n".join(out) + ("\n" if out else "")


def install_into(profile: Any, script_path: Any,
                 *, remove: bool = False) -> Optional[str]:
    """The new contents of `profile`, or None when nothing needs to change.

    Returns text rather than writing it, so the decision is testable without a
    profile on disk - and so the caller owns the one filesystem write.
    """
    from pathlib import Path

    path = Path(profile)
    try:
        current = path.read_text(encoding="utf-8") if path.is_file() else ""
    except OSError:
        return None

    if remove:
        stripped = strip_profile(current)
        return None if stripped == current else stripped

    if PROFILE_MARKER in current:
        return None                              # already there; install once
    tail = "" if not current or current.endswith("\n") else "\n"
    return f"{current}{tail}\n{profile_lines(script_path)}"
