r"""Regenerate `Leasha.pyproj` from what git tracks.

Run after adding or removing files:

    venv\Scripts\python.exe scripts\regen_vs_project.py

**Why this is generated rather than hand-maintained.** Visual Studio's Python
project shows only files it lists explicitly - unlike VS Code, which shows the
folder. With 228 Python files that list goes stale the first time somebody adds
a module, and a stale one is worse than none: the file is missing from Solution
Explorer, so it looks as though it does not exist, while the tests that import
it pass. Generating from `git ls-files` means the project shows exactly what is
under version control, which is the honest answer and needs no upkeep beyond
running this.

Visual Studio may rewrite the file when you add a file through the IDE. That is
fine - re-run this before committing and the ordering returns to normal.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parents[1]
PROJECT = ROOT / "Leasha.pyproj"

#: Stable, and it must stay stable: the solution file references the project by
#: this GUID, so changing it orphans the project inside the solution.
PROJECT_GUID = "{8B0E1F4A-3C7D-4A62-9E15-1D6C2A7B4E90}"

#: The GUI, not the CLI. F5 in Visual Studio should launch the application a
#: person actually uses; the CLI has launch profiles of its own below.
STARTUP_FILE = r"app\main.py"

#: Directories git tracks but Visual Studio should not present as source.
#: `logs` holds run output, not code.
SKIP_PREFIXES = ("logs/",)

#: Extensions Solution Explorer shows as content rather than compiling.
CONTENT_SUFFIXES = {
    ".md", ".toml", ".json", ".txt", ".sql", ".ps1", ".cmd", ".bat",
    ".ico", ".png", ".jpg", ".svg", ".example", ".yml", ".yaml", ".cfg", ".ini",
}


def tracked_files() -> list[str]:
    """Every tracked path, as Windows-separated strings."""
    result = subprocess.run(
        ["git", "ls-files"], cwd=ROOT, capture_output=True, text=True, check=True
    )
    paths = [
        line.strip() for line in result.stdout.splitlines()
        if line.strip() and not line.startswith(SKIP_PREFIXES)
    ]
    # **A set, because `git ls-files` repeats a path in a merge.** While a
    # merge still has conflicts, each unresolved file is listed once per
    # side (up to three times). Run then, the generator wrote CHANGELOG.md,
    # HANDOFF.md and docs\ORDER_REGISTER.md three times each into the file
    # committed in b248c9d, and test_vs_project failed on the next run.
    return sorted({path.replace("/", "\\") for path in paths})


def folders_of(paths: list[str]) -> list[str]:
    """Every directory that needs a `<Folder>` entry, parents included.

    Visual Studio does not infer intermediate folders: list `app\\ui\\widgets`
    without `app\\ui` and the tree renders wrong.
    """
    found: set[str] = set()
    for path in paths:
        parts = path.split("\\")[:-1]
        for depth in range(1, len(parts) + 1):
            found.add("\\".join(parts[:depth]))
    return sorted(found)


def render(paths: list[str]) -> str:
    compile_items: list[str] = []
    content_items: list[str] = []
    for path in paths:
        suffix = Path(path).suffix.lower()
        entry = f'    <{{tag}} Include="{escape(path)}" />'
        if suffix in {".py", ".pyw"}:
            compile_items.append(entry.format(tag="Compile"))
        elif suffix in CONTENT_SUFFIXES:
            content_items.append(entry.format(tag="Content"))

    folder_items = [
        f'    <Folder Include="{escape(folder)}" />' for folder in folders_of(paths)
    ]

    return f"""<?xml version="1.0" encoding="utf-8"?>
<!--
  Leasha - Visual Studio Python project.

  GENERATED by scripts/regen_vs_project.py from `git ls-files`. Re-run that
  after adding or removing files rather than editing this by hand; see the
  script's docstring for why the list is generated at all.
-->
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <SchemaVersion>2.0</SchemaVersion>
    <ProjectGuid>{PROJECT_GUID}</ProjectGuid>
    <ProjectHome>.</ProjectHome>
    <StartupFile>{STARTUP_FILE}</StartupFile>
    <SearchPath>.</SearchPath>
    <WorkingDirectory>.</WorkingDirectory>
    <OutputPath>.</OutputPath>
    <Name>Leasha</Name>
    <RootNamespace>Leasha</RootNamespace>
    <LaunchProvider>Standard Python launcher</LaunchProvider>
    <IsWindowsApplication>False</IsWindowsApplication>
    <!--
      The interpreter is the project's own venv, referenced relatively so the
      project works from any clone. If Visual Studio reports it missing, the
      venv has not been created yet: run install.ps1.
    -->
    <InterpreterId>MSBuild|venv|$(MSBuildProjectFullPath)</InterpreterId>
    <TestFramework>Pytest</TestFramework>
    <UnitTestRootDirectory>tests</UnitTestRootDirectory>
    <UnitTestPattern>test*.py</UnitTestPattern>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DebugSymbols>true</DebugSymbols>
    <EnableUnmanagedDebugging>false</EnableUnmanagedDebugging>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DebugSymbols>true</DebugSymbols>
    <EnableUnmanagedDebugging>false</EnableUnmanagedDebugging>
  </PropertyGroup>
  <ItemGroup>
{chr(10).join(folder_items)}
  </ItemGroup>
  <ItemGroup>
{chr(10).join(compile_items)}
  </ItemGroup>
  <ItemGroup>
{chr(10).join(content_items)}
  </ItemGroup>
  <ItemGroup>
    <Interpreter Include="venv\\">
      <Id>venv</Id>
      <Version>3.12</Version>
      <Description>venv (Python 3.12)</Description>
      <InterpreterPath>Scripts\\python.exe</InterpreterPath>
      <WindowsInterpreterPath>Scripts\\pythonw.exe</WindowsInterpreterPath>
      <PathEnvironmentVariable>PYTHONPATH</PathEnvironmentVariable>
      <Architecture>X64</Architecture>
    </Interpreter>
  </ItemGroup>
  <Import Project="$(MSBuildExtensionsPath32)\\Microsoft\\VisualStudio\\v$(VisualStudioVersion)\\Python Tools\\Microsoft.PythonTools.targets" />
</Project>
"""


def main() -> int:
    paths = tracked_files()
    PROJECT.write_text(render(paths), encoding="utf-8")
    compiled = sum(1 for p in paths if Path(p).suffix.lower() in {".py", ".pyw"})
    print(f"wrote {PROJECT.name}: {compiled} Python files, {len(paths)} tracked paths")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
