"""The Chat tab's decisions: what to say, how to number, what is on the shelf.

Layer: L5 (no Qt - the widgets in `app/ui/widgets/chat_*.py` only draw this)

Work order 202626270611 section 3. Everything here can be tested without a
display, which matters most for the two rules that are easy to break quietly:

* **Numbering is first-mention and never changes** (4e-2). `Numbering` hands
  out 1, 2, 3 in the order the answer first points at a source, and a number
  once given is never given again to something else - so the small raised
  number a reader is about to click is still the same source a moment later.
* **The shelf is exactly what the assistant may look at** (3c). `Shelf` is the
  one list; the tab draws it and the engine is told to search it first.

**No badges** (3a). Not one fixed string here warns that an answer "may be
wrong" - the honesty is in the receipts, not in a disclaimer. `test_chat_tab`
scans every string in the tab against `WARNING_WORDS`.
"""

from __future__ import annotations

import html
import re
import zlib
from dataclasses import dataclass, field
from typing import Any, Iterable, Optional

__all__ = [
    "Numbering", "Shelf", "ShelfItem", "MARKER", "WARNING_WORDS",
    "render_answer_html", "receipt_to_result", "closing_line",
    "unavailable_text", "title_from_question", "passage_html", "MAX_UNPINNED",
    "PLACEHOLDER", "EMPTY_HEADING", "EMPTY_HINT", "STOPPED_LINE", "FAILED_LINE",
    "NOT_BUILT_LINE", "SHELF_EMPTY", "speed_note", "THINKING_LINE", "RETRY_LABEL",
    "COPY_LABEL", "COPIED_LABEL", "REGENERATE_LABEL", "EDIT_LABEL", "NEW_CHAT_LABEL",
    "WEB_LABEL", "is_web_receipt", "WEB_OFF_TIP", "WEB_ON_TIP", "plain_answer_text",
]

# ---------------------------------------------------------------------------
# The fixed strings. Plain words: what it does, what to do next.
# ---------------------------------------------------------------------------

#: **Reworded on 2026-09-20 by the owner's instruction** (the Chat tab now talks like an
#: assistant and reads the files first): the old words were "Ask about your files and
#: mail. Enter sends; Shift+Enter starts a new line." and "Ask about anything you have
#: kept." - see the dated note in `docs/WORKORDER-202626270611-chat-tab.md`.
PLACEHOLDER = ("Ask about your files, or just talk. Enter sends; "
               "Shift+Enter starts a new line.")
EMPTY_HEADING = "Ask about your files, or just talk."
EMPTY_HINT = ("For example: What did we agree with the landlord about the "
              "deposit?  Show me the photos from the beach in 2015.  "
              "How many PDFs did Dave send in 2019?  What is a PST file?")
STOPPED_LINE = "Stopped. That is as far as it got."
THINKING_LINE = "Thinking..."
RETRY_LABEL = "Try again"
COPY_LABEL = "Copy"
COPIED_LABEL = "Copied"
REGENERATE_LABEL = "Regenerate"
EDIT_LABEL = "Edit"
NEW_CHAT_LABEL = "New chat"
WEB_LABEL = "Web"
WEB_OFF_TIP = ("Off: this conversation stays on this computer. Turn it on to let Chat also "
               "search the web for what your files do not say. Only a short search phrase "
               "leaves this computer, and you see it first.")
WEB_ON_TIP = ("On: after searching your files, Chat may search the web for what they do not "
              "say. Only a short search phrase leaves this computer - never your files or "
              "this conversation.")
FAILED_LINE = ("That did not work this time. Searching is not affected. "
               "Try asking again in a moment.")
NOT_BUILT_LINE = ("Chat is not part of this copy of Leasha yet. "
                  "Searching works exactly the same.")
SHELF_EMPTY = "Documents this chat uses will appear here."

#: A sentence to show when the helper program is missing, if the engine gave
#: no reason of its own. Says what to install and that search is unaffected.
_DEFAULT_UNAVAILABLE = (
    "Chat needs a free helper program called Ollama, running on this "
    "computer. Install it from ollama.com, start it, then press Check again. "
    "Searching works the same with or without it.")

#: Words that make a banner into a stigma. Nothing the tab says may match.
#: (3a: "No 'AI-generated, verify!' banners anywhere".) The test that reads
#: every fixed string in the tab imports this, so the list lives beside the
#: strings it polices.
WARNING_WORDS = (
    r"ai[- ]generated", r"generated by ai", r"\bverify\b", r"double[- ]check",
    r"may (?:be )?(?:inaccurate|incorrect|wrong)", r"can make mistakes",
    r"not (?:always )?(?:accurate|reliable)", r"hallucinat", r"disclaimer",
    r"use with caution", r"be careful", r"as an ai\b", r"\bbeta\b",
    r"experimental", r"\bwarning\b", r"check important",
)

#: Shelf items kept without being pinned. Pinned ones never drop off.
MAX_UNPINNED = 12

#: `[3]` - the marker the engine leaves in the prose where a source belongs.
MARKER = re.compile(r"\[(\d{1,3})\]")
_OPEN_MARKER_TAIL = re.compile(r"\[\d{0,3}$")


def unavailable_text(reason: str = "") -> str:
    """What the page says when there is no helper to answer. Never a trace."""
    reason = (reason or "").strip()
    return reason if reason else _DEFAULT_UNAVAILABLE


# ---------------------------------------------------------------------------
# Numbering - first mention, never changes
# ---------------------------------------------------------------------------

class Numbering:
    """Engine marker number -> the number the reader sees.

    Assigned in the order the prose first points at each source, so number 1
    is always the first thing the answer leaned on. Once assigned, fixed.
    """

    def __init__(self) -> None:
        self._map: dict[int, int] = {}

    def display(self, engine_number: int) -> int:
        if engine_number not in self._map:
            self._map[engine_number] = len(self._map) + 1
        return self._map[engine_number]

    def known(self, engine_number: int) -> Optional[int]:
        return self._map.get(engine_number)

    def feed(self, text: str) -> list[int]:
        """Number every marker in `text`; return the engine numbers that are new."""
        fresh: list[int] = []
        for match in MARKER.finditer(text or ""):
            number = int(match.group(1))
            if number not in self._map:
                fresh.append(number)
            self.display(number)
        return fresh

    def in_order(self) -> list[int]:
        """Engine numbers, in the order the reader met them."""
        return sorted(self._map, key=self._map.get)

    def __len__(self) -> int:
        return len(self._map)


def render_answer_html(text: str, numbering: Numbering,
                       linkable: Iterable[int] = ()) -> str:
    """The answer as small rich text: raised, clickable source numbers.

    A marker still arriving (`[1` at the very end of the text so far) is held
    back rather than drawn, so the reader never sees a number appear as
    brackets and then turn into a link. Text is escaped - an answer quoting a
    document containing `<b>` must not become markup.
    """
    text = _OPEN_MARKER_TAIL.sub("", text or "")
    can_link = set(linkable)
    out: list[str] = []
    last = 0
    for match in MARKER.finditer(text):
        out.append(html.escape(text[last:match.start()]))
        engine_number = int(match.group(1))
        shown = numbering.display(engine_number)
        if engine_number in can_link:
            out.append(f'<sup><a href="receipt:{shown}">{shown}</a></sup>')
        else:
            out.append(f"<sup>{shown}</sup>")
        last = match.end()
    out.append(html.escape(text[last:]))
    return "".join(out).replace("\n", "<br>")


# ---------------------------------------------------------------------------
# Receipts as result cards
# ---------------------------------------------------------------------------

def is_web_receipt(receipt: Any) -> bool:
    """A receipt the engine made from a web page (`locator == "Web"`, a `http(s)` address)."""
    return (str(getattr(receipt, "locator", "") or "") == WEB_LABEL
            and str(getattr(receipt, "path", "") or "").lower().startswith(("http://", "https://")))


def receipt_to_result(receipt: Any, rank: int) -> Any:
    """A `Receipt` as the `SearchResult` the results list already draws.

    The Sources pane is the same list search uses (3a), so the same row
    upgrades flow in without re-implementing any of them. A receipt with no
    file id (a mail message the index could not name) gets a stable negative
    one so two of them never fold into a single card.
    """
    from app.search.engine import SearchResult

    path = str(getattr(receipt, "path", "") or "")
    file_id = getattr(receipt, "file_id", None)
    if file_id is None:
        file_id = -(zlib.crc32(path.encode("utf-8", "replace")) % 1_000_000_000) - 1
    chunk_id = getattr(receipt, "chunk_id", None)
    if chunk_id is None:
        chunk_id = -1_000_000 - int(rank)
    quote = str(getattr(receipt, "quote", "") or "")
    if is_web_receipt(receipt) and quote:
        quote = "From the web: " + quote           # a web card says so in its own words
    return SearchResult(
        chunk_id=int(chunk_id), file_id=int(file_id), path=path,
        text=quote, score=1.0,
        rank=int(rank), label=str(getattr(receipt, "locator", "") or ""))


def passage_html(number: int, receipt: Any) -> str:
    """The exact passage a source stands on, for the strip under the list."""
    quote = html.escape(str(getattr(receipt, "quote", "") or ""))
    where = html.escape(str(getattr(receipt, "locator", "") or ""))
    name = html.escape(str(getattr(receipt, "name", "") or ""))
    head = f"<b>{number}</b> &nbsp;{name}" + (f" &middot; {where}" if where else "")
    return f"{head}<br><i>&ldquo;{quote}&rdquo;</i>"


# ---------------------------------------------------------------------------
# The shelf
# ---------------------------------------------------------------------------

@dataclass
class ShelfItem:
    path: str
    name: str
    file_id: Optional[int] = None
    pinned: bool = False


@dataclass
class Shelf:
    """The documents the assistant may look at, and only those (3c)."""

    items: list[ShelfItem] = field(default_factory=list)
    #: Paths the person took off. A later mention does not put them back;
    #: only an explicit add (a drag) does - out of scope means out of scope.
    removed: set[str] = field(default_factory=set)

    def _find(self, path: str) -> Optional[ShelfItem]:
        return next((i for i in self.items if i.path == path), None)

    def add(self, path: str, name: str = "", file_id: Optional[int] = None, *,
            explicit: bool = False) -> bool:
        """Put a document on the shelf. False if it is there or was removed."""
        if not path:
            return False
        if path in self.removed and not explicit:
            return False
        self.removed.discard(path)
        if self._find(path) is not None:
            return False
        tail = re.split(r"[\\/]", path)[-1]
        self.items.append(ShelfItem(path, name or tail, file_id, pinned=explicit))
        self._trim()
        return True

    def add_receipt(self, receipt: Any) -> bool:
        if is_web_receipt(receipt):          # a web page is not one of the person's documents
            return False
        return self.add(str(getattr(receipt, "path", "") or ""),
                        str(getattr(receipt, "name", "") or ""),
                        getattr(receipt, "file_id", None))

    def remove(self, path: str) -> None:
        self.items = [i for i in self.items if i.path != path]
        self.removed.add(path)

    def toggle_pin(self, path: str) -> bool:
        item = self._find(path)
        if item is None:
            return False
        item.pinned = not item.pinned
        return item.pinned

    def pin(self, path: str, name: str = "", file_id: Optional[int] = None) -> bool:
        """Pin a document, putting it on the shelf first if it is not there.
        What a right-click on a source does; True when it is pinned afterwards."""
        self.add(path, name, file_id, explicit=True)
        item = self._find(path)
        if item is None:
            return False
        item.pinned = True
        return True

    def _trim(self) -> None:
        loose = [i for i in self.items if not i.pinned]
        while len(loose) > MAX_UNPINNED:
            oldest = loose.pop(0)
            self.items.remove(oldest)

    def paths(self) -> list[str]:
        """Pinned first: what a follow-up searches before the rest."""
        ordered = sorted(self.items, key=lambda i: not i.pinned)
        return [i.path for i in ordered]

    def to_dict(self) -> dict:
        return {"items": [vars(i).copy() for i in self.items],
                "removed": sorted(self.removed)}

    @classmethod
    def from_dict(cls, data: Optional[dict]) -> "Shelf":
        data = data or {}
        items = [ShelfItem(str(d.get("path", "")), str(d.get("name", "")),
                           d.get("file_id"), bool(d.get("pinned", False)))
                 for d in data.get("items", ()) if d.get("path")]
        return cls(items, {str(p) for p in data.get("removed", ())})


# ---------------------------------------------------------------------------
# Small wording decisions
# ---------------------------------------------------------------------------

def closing_line(turn: Any, *, stopped: bool = False) -> str:
    """The quiet last line of an answer, when it needs one (4e-4).

    A FIND answer's grid says "That's all - N results." itself (the results
    list ends that way). What is left is the edge nothing else states: a
    search that found nothing, and an answer somebody cut short.
    """
    if stopped:
        return STOPPED_LINE
    if turn is None:
        return ""
    if getattr(turn, "partial", False):
        notes = [n for n in (getattr(turn, "notes", None) or []) if n and n != "stopped"]
        return notes[-1] if notes else STOPPED_LINE
    if getattr(turn, "kind", "") == "find" and not getattr(turn, "result_set", None):
        return "Nothing in what Leasha has indexed matches that."
    return ""


def plain_answer_text(text: str) -> str:
    """The answer as it should be copied: the words, without the `[n]` source
    markers (they mean nothing pasted anywhere else)."""
    return re.sub(r"\s*\[\d{1,3}(?:\s*[,;]\s*\d{1,3})*\]", "", text or "").strip()


def speed_note(modes: Any, explicit: str = "") -> str:
    """One plain line when Fast and Thoughtful would answer the same way, else "".

    They would when a `CHAT_MODEL` is set (it decides), or when only one model is
    installed. A control that changes nothing should say so; this is that
    sentence, shown beside the control and empty the rest of the time.
    """
    if explicit:
        return (f"Chat is set to use {explicit}, so Fast and Thoughtful answer the "
                "same way. Change that in Settings if you want a choice.")
    fast = (modes or {}).get("fast")
    if fast and fast == (modes or {}).get("thoughtful"):
        return (f"Only one model is installed ({fast}), so Fast and Thoughtful "
                "answer the same way.")
    return ""


def title_from_question(question: str, limit: int = 48) -> str:
    """A session's first name: the opening of the first question."""
    words = " ".join((question or "").split())
    if not words:
        return "New chat"
    if len(words) <= limit:
        return words
    cut = words[:limit].rsplit(" ", 1)[0] or words[:limit]
    return cut.rstrip(",.;:") + "..."
