"""One change, one transaction.

Layer: L3

`set_state` commits per key. The settings panel saves five ceilings together, so
that was five commits - five fsyncs on the UI thread - for one change nobody
thinks of as five. Combined with a signal on every spin-box notch, this is what
made the arrows feel dead.
"""

from __future__ import annotations

import pytest

from app.core import env_writer
from app.storage.sqlite_store import SqliteStore


@pytest.fixture
def store(tmp_path):
    with SqliteStore(tmp_path / "index.db") as opened:
        yield opened


def test_several_keys_land(store):
    store.set_states({"ui:a": "1", "ui:b": "2", "ui:c": "3"})
    assert store.get_state("ui:a") == "1"
    assert store.get_state("ui:c") == "3"


def test_it_overwrites_like_set_state_does(store):
    store.set_state("ui:a", "old")
    store.set_states({"ui:a": "new"})
    assert store.get_state("ui:a") == "new"


def test_an_empty_mapping_is_not_an_empty_transaction(store):
    """Called on every save, and most saves change nothing about a group. An
    empty write is still a commit."""
    store.set_states({})
    assert store.all_state().get("ui:a") is None


def test_values_are_stringified_like_the_single_key_path(store):
    """The UI passes ints for the ceilings. `set_state` takes str; if this took
    them raw, reading back would give int in one path and str in the other."""
    store.set_states({"ui:workers": 4})
    assert store.get_state("ui:workers") == "4"


def test_it_is_one_transaction(store, monkeypatch):
    """The whole point. Five commits for one change is five fsyncs on the UI
    thread, and holding an arrow made that fifty a second."""
    commits = []
    original = SqliteStore.write

    def counting(self):
        commits.append(1)
        return original(self)

    monkeypatch.setattr(SqliteStore, "write", counting)
    store.set_states({"ui:a": "1", "ui:b": "2", "ui:c": "3", "ui:d": "4", "ui:e": "5"})
    assert commits == [1]


# ---------------------------------------------------------------------------
# Removing a key, so the code default applies again
# ---------------------------------------------------------------------------

def test_none_removes_the_key(tmp_path):
    """The operation that did not exist, and whose absence froze every install.

    `.env` always beats the default in `config.py`. Without a way to remove a
    key, one written once was pinned for ever - the installer wrote
    `RERANK_MODEL=BAAI/bge-reranker-base` into every install and there was no
    action, in the UI or anywhere else, that could undo it. A default improved
    on a later measurement could never reach anybody.
    """
    path = tmp_path / ".env"
    path.write_text(
        "DATA_PATH=D:\\Data\n"
        "RERANK_MODEL=BAAI/bge-reranker-base\n"
        "RERANK_ENABLED=true\n",
        encoding="utf-8",
    )

    result = env_writer.apply_values(path, {"RERANK_MODEL": None})

    assert "RERANK_MODEL" not in result
    assert "RERANK_MODEL" not in path.read_text(encoding="utf-8")
    # Everything else survives.
    assert result["DATA_PATH"] == "D:\\Data"
    assert result["RERANK_ENABLED"] == "true"


def test_removing_a_key_that_is_absent_does_not_add_it(tmp_path):
    """`None` means "should not be set", not "set it to the string None".

    Appending `RERANK_MODEL=None` would be worse than doing nothing: it pins
    the key to a model name that does not exist.
    """
    path = tmp_path / ".env"
    path.write_text("DATA_PATH=D:\\Data\n", encoding="utf-8")

    result = env_writer.apply_values(path, {"RERANK_MODEL": None})

    assert "RERANK_MODEL" not in result
    assert "None" not in path.read_text(encoding="utf-8")


def test_removal_keeps_comments_and_order(tmp_path):
    """The non-destructive guarantee has to hold for removal too."""
    path = tmp_path / ".env"
    path.write_text(
        "# Generated by install.ps1\n"
        "DATA_PATH=D:\\Data\n"
        "\n"
        "# models\n"
        "EMBED_MODEL=BAAI/bge-small-en-v1.5\n"
        "RERANK_MODEL=BAAI/bge-reranker-base\n"
        "RERANK_ENABLED=true\n",
        encoding="utf-8",
    )

    env_writer.apply_values(path, {"RERANK_MODEL": None})
    text = path.read_text(encoding="utf-8")

    assert "# Generated by install.ps1" in text
    assert "# models" in text
    assert text.index("DATA_PATH") < text.index("EMBED_MODEL") < text.index("RERANK_ENABLED")
    assert "RERANK_MODEL" not in text


def test_a_removal_and_a_write_in_one_call(tmp_path):
    """Settings saves several keys at once; some may be resets."""
    path = tmp_path / ".env"
    path.write_text(
        "RERANK_MODEL=BAAI/bge-reranker-base\nRERANK_TOP_N=30\n", encoding="utf-8")

    result = env_writer.apply_values(
        path, {"RERANK_MODEL": None, "RERANK_TOP_N": 50, "RERANK_ENABLED": True})

    assert "RERANK_MODEL" not in result
    assert result["RERANK_TOP_N"] == "50"
    assert result["RERANK_ENABLED"] == "true"


def test_removing_a_key_restores_the_code_default(tmp_path):
    """The point of the whole thing, asserted end to end through Settings."""
    from app.core.config import Settings, load_settings

    path = tmp_path / ".env"
    path.write_text(
        f"DATA_PATH={tmp_path}\nRERANK_MODEL=BAAI/bge-reranker-base\n",
        encoding="utf-8")

    def loaded():
        return load_settings(path, create_dirs=True, check_writable=False)

    assert loaded().rerank_model == "BAAI/bge-reranker-base"

    env_writer.apply_values(path, {"RERANK_MODEL": None})

    # The declared default, rather than a hardcoded model name - this test
    # must keep passing when the default is next changed on a measurement,
    # which is the whole thing it exists to protect.
    default = Settings.model_fields["rerank_model"].default
    assert loaded().rerank_model == default
    assert default != "BAAI/bge-reranker-base"
