r"""Moving the index actually moves it, and `.env` follows.

Two bugs are pinned here, both of which shipped:

**The move that never happened.** Settings wrote `DATA_PATH` into `.env`,
recorded `index:pending_move`, and told the user the app would move the index on
the next start. Nothing read that key. The files stayed, the configuration
pointed elsewhere, and an intact index became unreferenced.

**The keys that outrank `DATA_PATH`.** `install.ps1` pins `VECTOR_PATH`,
`FTS_DB`, `CACHE_PATH`, `MODEL_CACHE` and `STATE_PATH` absolutely. `.env` beats a
default, so changing `DATA_PATH` alone moves nothing at all - the only visible
effect is Settings displaying a path the application is not using.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from app.core.env_writer import apply_values
from app.core.errors import AppErrorException
from app.core.index_move import (
    ADOPT,
    DERIVED_KEYS,
    FRESH,
    INDEX_SUBDIRS,
    MOVE,
    clear_pending,
    looks_like_an_index,
    perform_move,
    plan_move,
    read_pending,
    write_pending,
)

INSTALLER_ENV = """\
# Generated by install.ps1
DATA_PATH={data}
VECTOR_PATH={data}\\vectors
FTS_DB={data}\\fts\\knowledge.db
CACHE_PATH={data}\\cache
MODEL_CACHE={data}\\models
STATE_PATH={data}\\state
PROJECT_PATH=D:\\SearchProject
EMBED_MODEL=BAAI/bge-small-en-v1.5
"""


@pytest.fixture()
def index(tmp_path: Path) -> Path:
    """A populated index, with a recognisable file in each subdirectory."""
    root = tmp_path / "OldData"
    for name in INDEX_SUBDIRS:
        (root / name).mkdir(parents=True)
        (root / name / f"{name}.marker").write_text(name, encoding="utf-8")
    (root / "fts" / "knowledge.db").write_bytes(b"SQLite format 3\x00")
    return root


@pytest.fixture()
def env_file(tmp_path: Path, index: Path) -> Path:
    path = tmp_path / ".env"
    path.write_text(INSTALLER_ENV.format(data=str(index)), encoding="utf-8")
    return path


def env_values(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8-sig").splitlines():
        if line.strip() and not line.startswith("#") and "=" in line:
            key, _, value = line.partition("=")
            values[key.strip()] = value.strip()
    return values


# --- the move happens -------------------------------------------------------

def test_every_subdirectory_arrives(tmp_path: Path, index: Path, env_file: Path) -> None:
    destination = tmp_path / "Leasha" / "Data"
    perform_move(index, destination, MOVE, env_file)

    for name in INDEX_SUBDIRS:
        assert (destination / name / f"{name}.marker").read_text(encoding="utf-8") == name
    assert (destination / "fts" / "knowledge.db").is_file()


def test_the_old_location_is_left_empty_of_index_folders(
    tmp_path: Path, index: Path, env_file: Path
) -> None:
    """A move, not a copy. Leaving 100GB behind on a full drive is the whole
    reason somebody moves an index."""
    perform_move(index, tmp_path / "Leasha" / "Data", MOVE, env_file)
    assert not looks_like_an_index(index)


def test_a_destination_several_levels_deep_is_created(
    tmp_path: Path, index: Path, env_file: Path
) -> None:
    """`D:\\Leasha\\Data` where neither exists yet - the normal case."""
    destination = tmp_path / "brand" / "new" / "Data"
    perform_move(index, destination, MOVE, env_file)
    assert (destination / "vectors").is_dir()


# --- .env follows, including the keys that outrank DATA_PATH ----------------

def test_data_path_is_repointed(tmp_path: Path, index: Path, env_file: Path) -> None:
    destination = tmp_path / "Leasha" / "Data"
    perform_move(index, destination, MOVE, env_file)
    assert env_values(env_file)["DATA_PATH"] == str(destination)


@pytest.mark.parametrize("key", DERIVED_KEYS)
def test_the_pinned_subpaths_are_removed_not_rewritten(
    tmp_path: Path, index: Path, env_file: Path, key: str
) -> None:
    """**The bug that made a move look like a no-op.**

    These beat `DATA_PATH`, so leaving one behind silently keeps that part of
    the index on the old drive. Removing them makes them derive from
    `DATA_PATH`, which is also what stops this from recurring on the next move.
    """
    assert key in env_values(env_file), "the fixture should start pinned, like a real install"
    perform_move(index, tmp_path / "Leasha" / "Data", MOVE, env_file)
    assert key not in env_values(env_file)


def test_unrelated_settings_survive(tmp_path: Path, index: Path, env_file: Path) -> None:
    """`env_writer` preserves what it does not know about; this proves the move
    goes through it rather than rewriting the file."""
    perform_move(index, tmp_path / "Leasha" / "Data", MOVE, env_file)
    assert env_values(env_file)["EMBED_MODEL"] == "BAAI/bge-small-en-v1.5"


def test_env_is_written_after_the_files_move_not_before(
    tmp_path: Path, index: Path, env_file: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """**The ordering that decides whether a failure is recoverable.**

    Files first: a failed copy leaves `.env` pointing at the old location, which
    is intact, so the application starts normally. `.env` first is the case that
    orphans an index.
    """
    import app.core.index_move as module

    def explode(*args: object, **kwargs: object) -> None:
        raise OSError("the destination drive went away")

    monkeypatch.setattr(module.shutil, "move", explode)

    with pytest.raises(AppErrorException):
        perform_move(index, tmp_path / "Leasha" / "Data", MOVE, env_file)

    assert env_values(env_file)["DATA_PATH"] == str(index), (
        ".env was repointed despite the move failing - the index is now orphaned"
    )
    assert looks_like_an_index(index)


# --- refusals, before anything is touched -----------------------------------

def test_moving_onto_an_existing_index_is_refused(tmp_path: Path, index: Path) -> None:
    """Overwriting one index with another is not something to discover at 40GB."""
    destination = tmp_path / "Other"
    (destination / "vectors").mkdir(parents=True)

    with pytest.raises(AppErrorException) as caught:
        plan_move(index, destination, MOVE)
    assert "already contains an index" in caught.value.error.message


def test_moving_into_a_subfolder_of_itself_is_refused(tmp_path: Path, index: Path) -> None:
    """Either infinite recursion or a destroyed index, depending on the tool."""
    with pytest.raises(AppErrorException) as caught:
        plan_move(index, index / "vectors" / "nested", MOVE)
    assert "inside the current index folder" in caught.value.error.message


def test_moving_to_where_it_already_is_says_so(tmp_path: Path, index: Path) -> None:
    with pytest.raises(AppErrorException) as caught:
        plan_move(index, index, MOVE)
    assert "current location" in caught.value.error.message


def test_adopting_a_folder_with_no_index_is_refused(tmp_path: Path, index: Path) -> None:
    """Otherwise "use the index already there" silently means "lose this one"."""
    with pytest.raises(AppErrorException) as caught:
        plan_move(index, tmp_path / "empty", ADOPT)
    assert "does not contain an index" in caught.value.error.message


def test_moving_from_a_location_with_no_index_is_refused(tmp_path: Path) -> None:
    with pytest.raises(AppErrorException) as caught:
        plan_move(tmp_path / "nothing", tmp_path / "elsewhere", MOVE)
    assert "no index" in caught.value.error.message


def test_a_dry_run_changes_nothing(tmp_path: Path, index: Path, env_file: Path) -> None:
    report = plan_move(index, tmp_path / "Leasha" / "Data", MOVE)
    assert report.performed is False
    assert set(report.moved) == set(INDEX_SUBDIRS)
    assert looks_like_an_index(index)
    assert env_values(env_file)["DATA_PATH"] == str(index)
    assert not (tmp_path / "Leasha" / "Data").exists()


# --- adopt and fresh --------------------------------------------------------

def test_adopt_repoints_without_moving_anything(
    tmp_path: Path, index: Path, env_file: Path
) -> None:
    destination = tmp_path / "Existing"
    for name in INDEX_SUBDIRS:
        (destination / name).mkdir(parents=True)

    perform_move(index, destination, ADOPT, env_file)

    assert looks_like_an_index(index), "adopt must not touch the old index"
    assert env_values(env_file)["DATA_PATH"] == str(destination)


def test_fresh_creates_empty_subdirectories(
    tmp_path: Path, index: Path, env_file: Path
) -> None:
    destination = tmp_path / "Fresh"
    perform_move(index, destination, FRESH, env_file)

    for name in INDEX_SUBDIRS:
        assert (destination / name).is_dir()
        assert not any((destination / name).iterdir())
    assert looks_like_an_index(index), "fresh must not delete the old index"


# --- the pending record -----------------------------------------------------

def test_a_pending_move_round_trips(tmp_path: Path) -> None:
    write_pending(tmp_path, MOVE, Path(r"D:\Leasha\Data"))
    assert read_pending(tmp_path) == (MOVE, Path(r"D:\Leasha\Data"))


def test_no_pending_file_means_no_pending_move(tmp_path: Path) -> None:
    assert read_pending(tmp_path) is None


def test_a_corrupt_pending_file_is_ignored_rather_than_obeyed(tmp_path: Path) -> None:
    """Acting on garbage means moving an index somewhere nobody asked for.
    Ignoring it costs one extra click."""
    (tmp_path / "pending-move.json").write_text("{not json", encoding="utf-8")
    assert read_pending(tmp_path) is None


def test_an_unknown_action_is_ignored(tmp_path: Path) -> None:
    (tmp_path / "pending-move.json").write_text(
        json.dumps({"action": "delete-everything", "destination": "D:\\x"}),
        encoding="utf-8",
    )
    assert read_pending(tmp_path) is None


def test_clearing_is_safe_when_there_is_nothing_to_clear(tmp_path: Path) -> None:
    clear_pending(tmp_path)
    clear_pending(tmp_path)


def test_the_record_does_not_live_inside_the_index(tmp_path: Path, index: Path) -> None:
    """It is read before any store opens, and it must survive the move - so it
    cannot be a row in the database that is being moved."""
    write_pending(tmp_path, MOVE, tmp_path / "new")
    assert (tmp_path / "pending-move.json").is_file()
    assert not (index / "pending-move.json").exists()


# --- the settings registry and the mover agree ------------------------------

def test_the_derived_keys_match_the_configuration_that_reads_them() -> None:
    """If `config.py` gains a sixth per-directory override, this fails - rather
    than that directory quietly staying behind on the next move."""
    from app.core import config as config_module

    source = Path(config_module.__file__).read_text(encoding="utf-8")
    for key in DERIVED_KEYS:
        assert f'"{key}"' in source, f"{key} is no longer read by config.py"


def test_index_subdirs_match_config() -> None:
    from app.core.config import _INDEX_SUBDIRS

    assert set(INDEX_SUBDIRS) == set(_INDEX_SUBDIRS)
