r"""Generate a new extractor: the module, the import, the pin.

Layer: L0

Adding a file type that needs its own parser is six steps, five of which are
identical every time and one of which is the actual work. The five are where it
goes wrong - forget the line in `app/extract/_readers.py` and `register()` never
runs, so the extension reports as unsupported and nothing anywhere says why.
(That list of imports lived in `app/extract/__init__.py` until work order 0r
item 2b moved it one file sideways, so that importing the package no longer
imports every parser before the window is on screen. The line is the same line,
in the same alphabetical place; only the file it goes in changed.)

**This generates the five and leaves the one.** The module arrives with the
contract already correct - lazy import, declared `requires`, errors as values,
never an empty document - and a single `TODO` where the parsing goes.

**It writes into the application's own source tree**, which is a serious thing
for a running program to do, so:

* Nothing is written until `apply()` is called, and `plan()` returns exactly
  what would change so it can be shown first.
* An existing file is never overwritten. A name already taken is refused, with
  the path that holds it.
* Every edit is append-or-insert at a known anchor, never a rewrite - a
  generator that reformats `_readers.py` would eventually eat something.
* A frozen build has no source tree to write to and refuses outright rather
  than writing into a temporary directory nobody will ever look at.

The generated module is deliberately verbose. Somebody reading it in six months
is more likely to be maintaining it than admiring it.
"""

from __future__ import annotations

import keyword
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from app.core.errors import AppErrorException, make_error

__all__ = [
    "ExtractorSpec",
    "ScaffoldPlan",
    "FileChange",
    "plan",
    "apply",
    "project_root",
    "MODULE_TEMPLATE",
]

#: A reader name has to be a valid Python identifier *and* readable in config,
#: where it appears as `extractor = "name"`.
_NAME = re.compile(r"^[a-z][a-z0-9_]{1,30}$")

#: `.dxf`, `.tar.gz` is not supported - the registry keys on `Path.suffix`,
#: which is the last component only.
_EXTENSION = re.compile(r"^\.[a-z0-9][a-z0-9+-]{0,15}$")


def project_root() -> Path:
    """The repository root: the folder holding `app/` and `requirements.txt`."""
    return Path(__file__).resolve().parents[2]


def _fail(reason: str, *, suggestion: str = "") -> None:
    raise AppErrorException(make_error(
        "ERR_CONFIG_INVALID", "core.scaffold",
        key="new file type", reason=reason, suggestion=suggestion,
    ))


@dataclass(frozen=True, slots=True)
class ExtractorSpec:
    """What the person answered. Everything else is derived."""

    name: str                       # reader name, e.g. "cad"
    extensions: tuple[str, ...]     # (".dxf",)
    module: str = ""                # import name, e.g. "ezdxf" - blank if none
    package: str = ""               # pip name, e.g. "ezdxf"
    provides: str = ""              # what is lost without it
    hard: bool = True               # no library -> nothing readable at all?
    reads_externally: bool = False  # read through another application
    max_bytes: int = 0              # 0 -> use the default cap
    version: str = ""               # pin, e.g. "1.4.2" - blank for unpinned

    @property
    def module_file(self) -> str:
        return f"{self.name}.py"

    @property
    def class_name(self) -> str:
        return f"{self.name.title().replace('_', '')}Extractor"


@dataclass(frozen=True, slots=True)
class FileChange:
    """One file to create or amend, with the text that would end up in it."""

    path: Path
    content: str
    action: str                     # "create" | "amend"
    summary: str = ""


@dataclass(frozen=True, slots=True)
class ScaffoldPlan:
    """Everything that would change, and nothing done yet."""

    spec: ExtractorSpec
    changes: list[FileChange] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)

    @property
    def paths(self) -> list[Path]:
        return [change.path for change in self.changes]


# ---------------------------------------------------------------------------
# The template
# ---------------------------------------------------------------------------

MODULE_TEMPLATE = '''r"""{title}

Layer: L2

Generated by Settings -> File types -> Add file type. The contract below is
already correct; the parsing is the part to write.

**The rules that matter, and why:**

* The library is imported **inside** `extract()`. At module level, a machine
  without it fails to start the whole application instead of one file type
  reporting a fix.
* Failure is a value, not an exception. A corrupt file in a 100GB run is
  Tuesday: raise `AppErrorException` (via `raise_error`) for a file that cannot
  be read at all, and attach `builder.warn(...)` for a file that is readable but
  degraded - it still gets indexed.
* Never yield an empty document. `extract()` treats empty as
  `ERR_NO_TEXT_LAYER` and the file leaves the index entirely. If it is still
  worth finding by name, emit the name with a warning saying why the contents
  are missing.
"""

from __future__ import annotations

from pathlib import Path
from typing import Iterable

from app.core.errors import make_error, raise_error
from app.core.format_health import Requirement
from app.extract.base import Document, DocumentBuilder, register


class {class_name}:
    """{summary}"""

    name = "{name}"
    extensions = frozenset({{{extensions}}})
    reads_externally = {reads_externally}
{requires_block}
    def supports(self, path: Path) -> bool:
        return path.suffix.lower() in self.extensions

    def extract(self, path: Path) -> Iterable[Document]:
{import_block}
        builder = DocumentBuilder(path)

        # ------------------------------------------------------------------
        # TODO: read `path` and add what is worth searching.
        #
        #   builder.add(text, page=1, label="Section name", prefix_label=True)
        #
        # `page` reaches the `chunks.page` column, so a result can say where in
        # the file it came from. `label` names it on screen; `prefix_label=True`
        # also writes the label into the indexed text, which is how a sheet or
        # slide name becomes searchable - there is no column for it.
        #
        # Offsets are maintained for you: `DocumentBuilder` records each
        # segment's position as it appends, so highlighting keeps working.
        # ------------------------------------------------------------------
        raise NotImplementedError(
            "{name}: the reader is scaffolded but not written yet"
        )

        document = builder.build()
        if document.is_empty:
            yield self._name_only(path, "No text could be read from this file.")
            return
        yield document

    def _name_only(self, path: Path, reason: str) -> Document:
        """The file as its name, when the contents cannot be read.

        Never an empty document: empty means the file disappears from the index
        altogether, and a file somebody searches for by name is exactly the one
        that must not.
        """
        builder = DocumentBuilder(path)
        builder.add(path.stem.replace("_", " ").replace("-", " "), label="File name")
        builder.warn(make_error(
            "ERR_NO_TEXT_LAYER", "extract.{name}",
            path=str(path), details=reason,
            suggestion="The file is indexed by its name.",
        ))
        return builder.build()


register({class_name}())
'''

_REQUIRES_BLOCK = '''    #: Declared so Settings and `doctor.py` can report this format's real state
    #: and offer the exact install command, instead of leaving somebody to infer
    #: a missing package from an empty result set.
    requires = (
        Requirement("{module}", "{package}",
                    provides="{provides}",
                    hard={hard}),
    )
'''

_IMPORT_BLOCK = '''        try:
            import {module}  # noqa: PLC0415 - lazy by design, see the docstring
        except ImportError:
            raise_error(
                "ERR_UNSUPPORTED_TYPE", "extract.{name}",
                path=str(path), ext=path.suffix.lower(),
                suggestion=r"venv\\Scripts\\pip install {package}",
            )
'''

_NO_IMPORT_BLOCK = '''        # No third-party library: this reads the file with the standard library.
'''


# ---------------------------------------------------------------------------
# Planning
# ---------------------------------------------------------------------------

def _validate(spec: ExtractorSpec, root: Path) -> None:
    if not _NAME.match(spec.name):
        _fail(
            f"{spec.name!r} is not a usable reader name",
            suggestion="Lower case, starting with a letter, letters/digits/"
                       "underscores only - for example 'cad' or 'auto_cad'.",
        )
    if keyword.iskeyword(spec.name):
        _fail(f"{spec.name!r} is a Python keyword and cannot be a module name")

    if not spec.extensions:
        _fail("no file extension was given",
              suggestion="At least one, for example '.dxf'.")

    for extension in spec.extensions:
        if not _EXTENSION.match(extension):
            _fail(
                f"{extension!r} is not a file extension",
                suggestion="Lower case, one leading dot, no spaces - '.dxf'.",
            )

    if spec.package and not spec.module:
        _fail("a package was named but not the module to import",
              suggestion="For python-docx the import is 'docx'; for pymupdf it "
                         "is 'fitz'. They are frequently different.")

    target = root / "app" / "extract" / spec.module_file
    if target.exists():
        _fail(f"{target.name} already exists",
              suggestion=f"Choose another name, or edit {target} directly.")

    taken = _claimed_extensions(root)
    for extension in spec.extensions:
        if extension in taken:
            _fail(
                f"{extension} is already read by the {taken[extension]!r} reader",
                suggestion="Two readers claiming one extension is refused at "
                           "startup. Edit that reader instead, or choose a "
                           "different extension.",
            )


def _claimed_extensions(root: Path) -> dict[str, str]:
    """Extension -> reader name, from the live registry when it can be read.

    Best effort: a partially broken tree must not stop the generator, and the
    duplicate claim would then be caught at startup instead - later, but never
    silently.
    """
    try:
        import app.extract  # noqa: F401 - registration side effects
        from app.extract.base import REGISTRY

        return {
            extension: str(getattr(extractor, "name", "?"))
            for extension, extractor in REGISTRY.items()
        }
    except Exception:                              # noqa: BLE001
        return {}


def _render_module(spec: ExtractorSpec) -> str:
    extensions = ", ".join(f'"{extension}"' for extension in spec.extensions)
    listed = ", ".join(spec.extensions)

    if spec.module:
        requires = _REQUIRES_BLOCK.format(
            module=spec.module,
            package=spec.package or spec.module,
            provides=spec.provides or "the contents of these files",
            hard="True" if spec.hard else "False",
        )
        imports = _IMPORT_BLOCK.format(
            module=spec.module,
            name=spec.name,
            package=spec.package or spec.module,
        )
    else:
        requires = ""
        imports = _NO_IMPORT_BLOCK

    return MODULE_TEMPLATE.format(
        title=f"{listed} files, read for their text.",
        class_name=spec.class_name,
        summary=f"{listed} files.",
        name=spec.name,
        extensions=extensions,
        reads_externally=spec.reads_externally,
        requires_block=requires,
        import_block=imports,
    )


def _amend_init(root: Path, spec: ExtractorSpec) -> Optional[FileChange]:
    """Insert the import that makes `register()` actually run.

    **The step that is forgotten**, and its failure mode is the worst kind:
    the module is perfect, the extension reports unsupported, and nothing
    connects the two. Inserted in alphabetical order among the existing
    extractor imports so the file stays as it was written.

    The file is `app/extract/_readers.py`, not the package's `__init__.py`:
    see this module's own docstring, and `_readers.py`'s.
    """
    path = root / "app" / "extract" / "_readers.py"
    text = path.read_text(encoding="utf-8")
    line = f"from app.extract import {spec.name} as {spec.name}  # noqa: F401,E402"

    if line in text:
        return None

    lines = text.splitlines()
    marker = "from app.extract import "
    positions = [i for i, entry in enumerate(lines) if entry.startswith(marker)]
    if not positions:
        _fail(
            "app/extract/_readers.py has no extractor imports to insert beside",
            suggestion=f"Add this line by hand:  {line}",
        )

    insert_at = positions[-1] + 1
    for position in positions:
        existing = lines[position][len(marker):].split(" ")[0]
        if existing > spec.name:
            insert_at = position
            break

    lines.insert(insert_at, line)
    return FileChange(
        path=path,
        content="\n".join(lines) + "\n",
        action="amend",
        summary=f"import {spec.name} so register() runs",
    )


def _amend_requirements(root: Path, spec: ExtractorSpec) -> Optional[FileChange]:
    """Pin the package, so the next machine installs it too."""
    if not spec.package:
        return None

    path = root / "requirements.txt"
    text = path.read_text(encoding="utf-8")
    if re.search(rf"^{re.escape(spec.package)}\b", text, re.MULTILINE):
        return None

    pin = f"{spec.package}=={spec.version}" if spec.version else spec.package
    listed = ", ".join(spec.extensions)
    addition = (
        f"\n{pin}"
        f"{' ' * max(1, 22 - len(pin))}# {listed} - added by Settings\n"
    )
    return FileChange(
        path=path,
        content=text.rstrip("\n") + "\n" + addition,
        action="amend",
        summary=f"pin {pin}",
    )


def plan(spec: ExtractorSpec, root: Optional[Path] = None) -> ScaffoldPlan:
    """What adding this reader would change. Writes nothing.

    Raises `AppErrorException` with a usable suggestion for anything that would
    not work - a name already taken, an extension another reader claims, an
    extension that is not one.
    """
    root = Path(root) if root else project_root()

    if getattr(sys, "frozen", False):
        _fail(
            "this is a packaged build, which has no source tree to add a reader to",
            suggestion="Add the file type in a development checkout, then "
                       "rebuild. Existing formats can still be configured here.",
        )

    _validate(spec, root)

    changes = [FileChange(
        path=root / "app" / "extract" / spec.module_file,
        content=_render_module(spec),
        action="create",
        summary=f"the {spec.name} reader for {', '.join(spec.extensions)}",
    )]

    for change in (_amend_init(root, spec), _amend_requirements(root, spec)):
        if change is not None:
            changes.append(change)

    notes = [
        f"Open app/extract/{spec.module_file} and replace the TODO with the "
        "parsing - everything around it is already correct.",
        "Restart the application: extractors register on import, so a new one "
        "is not picked up by a running process.",
    ]
    if spec.package:
        notes.insert(0, f"Install the library: venv\\Scripts\\pip install {spec.package}")
    if spec.max_bytes:
        notes.append(
            f"Set the size cap to {spec.max_bytes // (1 << 20)}MB in Settings "
            "once the reader is working."
        )

    return ScaffoldPlan(spec=spec, changes=changes, notes=notes)


def apply(scaffold: ScaffoldPlan) -> list[Path]:
    """Write the plan. Returns the paths written, in order.

    Creates are checked again immediately before writing: a plan can be shown
    on screen for as long as somebody takes to read it, and a file that
    appeared in the meantime must not be overwritten by a stale decision.
    """
    written: list[Path] = []
    for change in scaffold.changes:
        if change.action == "create" and change.path.exists():
            _fail(f"{change.path.name} appeared while the plan was on screen",
                  suggestion="Nothing was overwritten. Choose another name.")
        change.path.parent.mkdir(parents=True, exist_ok=True)
        temporary = change.path.with_suffix(change.path.suffix + ".tmp")
        temporary.write_text(change.content, encoding="utf-8")
        temporary.replace(change.path)
        written.append(change.path)
    return written
